CREATE TABLE user 
(userID int AUTO_INCREMENT PRIMARY KEY UNIQUE, username VARCHAR(100) UNIQUE NOT NULL, 
password VARCHAR(100) NOT NULL, firstname VARCHAR(100) NOT NULL, lastname VARCHAR(100) NOT NULL, 
email VARCHAR(100) UNIQUE NOT NULL);